# config/services.yaml

- "My Apps":
    - "SillyTavern":
        href: "https://st.4lite.win/"
        description: "The main event"
        icon: "brain"

- "Server Management":
    - "Cloudflare":
        href: "https://dash.cloudflare.com/"
        description: "Domain & Security"
        icon: "cloudflare"
    - "Oracle Cloud":
        href: "https://cloud.oracle.com/"
        description: "The Server"
        icon: "oracle"
